# rnn_config.yaml
model:
  type: "attention"
  rnn_units: 128

training:
  learning_rate: 0.001
  batch_size: 1024
  epochs: 10
  validation_split: 0.2

data:
  en_path: "data/small_vocab_en"
  fr_path: "data/small_vocab_fr"
  save_dir: "saved_models/attention"
